# file: postgresql/tasks/configure.yml

- name: PostgreSQL | Make sure the postgres data directory exists
  file:
    path: "{{postgresql_data_directory}}"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    state: directory
    mode: 0700
  register: pgdata_dir_exist

- name: PostgreSQL | Stat data directory cluster
  stat:
    path: "{{ postgresql_data_directory }}/{{ postgresql_version }}/{{ postgresql_cluster_name }}"
    get_md5: no
  register: stat_postgresql_data_directory

- name: PostgreSQL | Stop service if data directory cluster does not exist
  service:
    name: postgresql
    state: stopped
  when: >
    postgresql_data_directory_auto_create
    and not stat_postgresql_data_directory.stat.exists

- name: PostgreSQL | Create data directory cluster
  shell: /usr/lib/postgresql/{{ postgresql_version }}/bin/initdb -D {{ postgresql_data_directory }}/{{ postgresql_version }}/{{ postgresql_cluster_name }}
  when: >
    postgresql_data_directory_auto_create
    and not stat_postgresql_data_directory.stat.exists

- name: PostgreSQL | Ensure the locale is generated
  locale_gen: name={{postgresql_locale}} state=present

- name: PostgreSQL | Reset the cluster - drop the existing one
  shell: pg_dropcluster --stop {{postgresql_version}} {{postgresql_cluster_name}}
  when: postgresql_cluster_reset and pgdata_dir_exist.changed

- name: PostgreSQL | Reset the cluster - create a new one (with specified encoding and locale)
  shell: pg_createcluster --start --locale {{postgresql_locale}} -e {{postgresql_encoding}} -d {{postgresql_data_directory}} {{postgresql_version}} {{postgresql_cluster_name}}
  when: postgresql_cluster_reset and pgdata_dir_exist.changed

- name: PostgreSQL | Update configuration - pt. 1 (pg_hba.conf)
  template:
    src: pg_hba.conf.j2
    dest: "{{postgresql_conf_directory}}/pg_hba.conf"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0640
  register: postgresql_configuration_pt1

- name: PostgreSQL | Update configuration - pt. 2 (postgresql.conf)
  template:
    src: "postgresql.conf-{{ postgresql_version }}.j2"
    dest: "{{postgresql_conf_directory}}/postgresql.conf"
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0640
  register: postgresql_configuration_pt2

- name: PostgreSQL | Create folder for additional configuration files
  file:
    name: "{{postgresql_conf_directory}}/conf.d"
    state: directory
    owner: "{{ postgresql_service_user }}"
    group: "{{ postgresql_service_group }}"
    mode: 0755

- name: PostgreSQL | Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
  when: postgresql_configuration_pt1.changed or postgresql_configuration_pt2.changed

- name: PostgreSQL | Create admin user
  shell: >
    /usr/lib/postgresql/{{ postgresql_version }}/bin/createuser -s -d -r {{ postgresql_admin_user }}
  register: create_admin_user_result
  changed_when: >
    create_admin_user_result.rc == 0
  failed_when: >
    create_admin_user_result.rc != 0
    and 'role "{{ postgresql_admin_user }}" already exists' not in create_admin_user_result.stderr

- name: PostgreSQL | Create admin user database
  shell: >
    /usr/lib/postgresql/{{ postgresql_version }}/bin/createdb -U {{ postgresql_admin_user }} -O {{ postgresql_admin_user }} {{ postgresql_admin_user }}
  register: create_admin_user_db_result
  changed_when: >
    create_admin_user_db_result.rc == 0
  failed_when: >
    create_admin_user_db_result.rc != 0
    and 'database "{{ postgresql_admin_user }}" already exists' not in create_admin_user_db_result.stderr